### ISSUE TITLE
Crash upon attempting to place seeds on Resurgent Farmland

### ISSUE THREAD

**Issue by mintynoura** [rotgruengelb/MyNethersDelightRefabricated#1]
*Versions:*
Minecraft 1.20.1
Fabric Loader 0.16.4
My Nether's Delight Refabricated 0.1.0.1+0.1.7.5
Fabric API 0.92.2+1.20.1

*Bug:*
The game hard crashes when trying to plant wheat seeds on Resurgent Farmland

*Logs:*
[Crash report](https://mclo.gs/zPM35o7)
[latest.log](https://mclo.gs/9FlxxXJ)

**Comment by ChrysanthCow** [comment]
Will fix this a little later. Sorry.

**Comment by mintynoura** [comment]
it's no worries, don't be sorry!
