### ISSUE TITLE
[1.21.1] Crash with conflicting mods.

### ISSUE THREAD

**Issue by Akinesis** [rotgruengelb/MyNethersDelightRefabricated#6]
The mods create crashes with multiple mods.

The culprite seams to be related to berry bushed or adjacent, as multiple mod conflicts around thos mixins.

I som mod that independantly cause crashes : 

- [Barklings](https://modrinth.com/mod/barklings)
- [Frights and foliage](https://modrinth.com/mod/frights-and-foliage)
- [Diversity](https://modrinth.com/mod/faewufs-diversity)

I suspect many more are involed but as i foud taht Nether Delights was responsible for the crash, i've sopted investigating further :)
Love the mod, by the way.

**Comment by suerion** [comment]
@MerchantPug had the same issue, the Mod conflict on me, with a lot of Mods,

After Disabling the Mod, the Client does not crash anymore.

Barkling https://github.com/Nasache/barklings-V1.21/issues/7#issuecomment-2510202149
Oh the Biomes We've gone https://github.com/Potion-Studios/Oh-The-Biomes-Weve-Gone
All the Wood Weve Got https://github.com/Potion-Studios/All-The-Wood-Weve-Got/issues/9
Biomes of Plenty https://github.com/Glitchfiend/BiomesOPlenty
Glitchcore Library https://github.com/Glitchfiend/GlitchCore

You could look on the issues of Barklings and All the Wood Weve Got, there are log files. But it is not an issue on there side, only with your Mod it crash.

**Comment by ChrysanthCow** [comment]
Please give logs. I can't debug without proper logs.

**Comment by suerion** [comment]
Hey, it says allways that an other mod has an issue on entry

Client latest log with barklings:

https://mclo.gs/2LEgvm8

**Comment by suerion** [comment]
Here the crash log -> https://mclo.gs/aWq5997

**Comment by ChrysanthCow** [comment]
Okay, I'm pretty sure I know the fix.

Thanks for the reports!

**Comment by ChrysanthCow** [comment]
This was me not realizing that Fabric had a way to implement sign and hanging sign materials.
Thanks for the bug report, should be fixed next update.

**Comment by ChrysanthCow** [comment]
Will be fixed in 1.1.1
