### ISSUE TITLE
crash on startup, is fixed when removing my nethers delight refabricated

### ISSUE THREAD

**Issue by toastedfoxx** [rotgruengelb/MyNethersDelightRefabricated#8]
https://mclo.gs/3yMScZh

**Comment by suerion** [comment]
Hey, i had the same issue here, there is some issues on Mixin startup on Client, Server works smooth.

Here the latest log

https://mclo.gs/0n4negu

@MerchantPug thanks for your work, only a little issues is given now :), hope you would find the fix, if you had a build to test, give it to me, i will try it on my dev enviroment ;)

**Comment by ChrysanthCow** [comment]
ah yeah, I forgot to remove something from a file. mb.

**Comment by ChrysanthCow** [comment]
Should be fixed as of 1.1.2
